### ISSUE TITLE
Hello from lsp-bridge

### ISSUE THREAD

**Issue by manateelazycat** [iamcco/ds-pinyin-lsp#7]
你好， 我是 lsp-bridge https://github.com/manateelazycat/lsp-bridge 的作者， 今天添加了对 ds-pinyin 的支持： https://github.com/manateelazycat/lsp-bridge/commit/476b0da6d0256ca8af9e1a527fd03fa5f6646492

能否在 README 中添加 lsp-bridge 的连接？ 方便 Emacs 用户也能使用 ds-pinyin . ;)

**Comment by iamcco** [comment]
已经加了 🙏
